version: '3.8'

services:
  whatsapp-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fresh-whatsapp-bot
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Bot Configuration
      - BOT_NAME=${BOT_NAME:-Fresh WhatsApp Bot}
      - PREFIX=${PREFIX:-.}
      - MODE=${MODE:-public}
      
      # Session & Owner
      - SESSION_ID=${SESSION_ID}
      - OWNER_NUMBER=${OWNER_NUMBER}
      - OWNER_NAME=${OWNER_NAME:-Bot Owner}
      
      # Features
      - AUTO_READ=${AUTO_READ:-true}
      - AUTO_REACT=${AUTO_REACT:-true}
      - AUTO_BIO=${AUTO_BIO:-true}
      - WELCOME=${WELCOME:-true}
      - ANTILINK=${ANTILINK:-false}
      - REJECT_CALL=${REJECT_CALL:-true}
      
      # Server
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      - TIMEZONE=${TIMEZONE:-Africa/Lagos}
      
      # Optional API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    
    volumes:
      # Persist session data
      - ./session:/app/session
      # Persist logs
      - ./logs:/app/logs
      # Persist temp files
      - ./temp:/app/temp
    
    networks:
      - bot-network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.2'

networks:
  bot-network:
    driver: bridge
